import { Toaster } from "sonner"

import { TailwindIndicator } from "@/components/core/TailwindIndicator"

import ConvexClientProvider from "./ConvexClientProvider"

import "../styles/app.scss"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="inter min-h-screen bg-body text-white">
        <Toaster />
        <ConvexClientProvider>{children}</ConvexClientProvider>
        <TailwindIndicator />
      </body>
    </html>
  )
}
